kind: Service
apiVersion: v1
metadata:
  name: foo-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: foo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
